# Run tests with combinations of major dependency releases.
#
# For numpy, the C API version matters:
# https://github.com/numpy/numpy/blob/main/numpy/_core/code_generators/cversions.txt

name: Compat tests

on:
  # quite a few jobs, so let's not run this on every push
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compat_tests.yml'

      # source files
      - 'aio_overpass/**.py'
      - 'test/**.py'

      # dependency changes
      - 'pyproject.toml'
      - 'uv.lock'
    
jobs:
  compat-test:
    name: Test with pinned deps
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12", "3.13", "3.14", "3.14t"]
        aiohttp: ["3.13.0"]
        joblib: ["1.5.2"]
        networkx: ["3.4.2", "3.5"]
        numpy: ["2.2.6", "2.3.3"]
        shapely: ["2.0.7", "2.1.2"]
        exclude:
          - python: "3.14"
            numpy: "2.2.6"
          - python: "3.14t"
            numpy: "2.2.6"
    steps:
      - name: Install GEOS (in case there are no shapely wheels)
        run: sudo apt install libgeos-dev

      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python }}

      - name: Install dependencies & library
        run: |
          uv sync --all-extras --dev
          uv add aiohttp==${{ matrix.aiohttp }} --extra speedups
          uv add joblib==${{ matrix.joblib }}
          uv add networkx==${{ matrix.networkx }}
          uv add shapely==${{ matrix.shapely }}
          uv add numpy==${{ matrix.numpy }}

      - name: Test with pytest
        run: uv run invoke test
