name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0,6,12,18 * * *'  # run four times a day
  push:
    paths:
      - '.github/workflows/integration_tests.yml'
      - 'test/integration/**.py'

jobs:
  script:
    name: Run integration test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11"]
        file: [
          "any_element_barmbek_nord",
          "any_element_carabanchel",
          "any_element_city_of_london",
          "any_route_barmbek_nord",
          "any_route_carabanchel",
          "any_route_city_of_london",
        ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.11"

      - name: Install dependencies & library
        run: uv sync --all-extras --dev

      - name: Run test
        run: uv run python -m test.integration.${{ matrix.file }}
