name: Publish new version

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    name: Test package
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies & library
        run: uv sync --all-extras --dev

      - name: Test with pytest
        run: uv run invoke test

      - name: Generate docs with pdoc
        run: uv run pdoc -o ./doc aio_overpass/

  build:  # separate building from publishing since the publishing job has more permissions
    name: Build distributions
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test  # do not publish if tests fail
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/aio-overpass
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build the distributions
        run: uv build

      - name: Store the distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-package:
    name: Publish new release on PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    permissions:
      contents: read
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/aio-overpass
    steps:
      - name: Download the distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-docs:
    name: Deploy documentation to Pages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: publish-package  # do not publish docs if release is not published
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: "3.11"

      - name: Install dependencies & library
        run: uv sync --all-extras --dev

      - name: Generate docs with pdoc
        run: uv run pdoc -o ./doc aio_overpass/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
