name: Test and lint package

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - 'aio_overpass/**.py'
      - 'examples/**.ipynb'
      - 'test/**.py'
      - 'test/**.json'
      - 'test/**.json.gz'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'tasks.py'

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies & library
        run: poetry install --all-extras --no-interaction

      - name: Test with pytest
        run: poetry run invoke test

      - name: Generate docs with pdoc
        run: poetry run pdoc -o ./doc aio_overpass/

  coverage:
    name: Upload test coverage to Codecov (3.10)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Install dependencies & library
        run: poetry install --all-extras --no-interaction

      - name: Test with pytest
        run: poetry run invoke test-cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint package (3.10)
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Check if pyproject.toml consistent with poetry.lock
        run: poetry check --lock --no-interaction

      - name: Install dependencies & library
        run: poetry install --all-extras --no-interaction

      - name: Check formatting with Ruff
        run: poetry run ruff format aio_overpass/ --check

      - name: Lint with Ruff
        run: poetry run ruff check aio_overpass/

      - name: Check types with mypy
        run: poetry run mypy aio_overpass/

      - name: Check types with pyright
        run: poetry run pyright aio_overpass/

      - name: Validate __slots__
        run: poetry run slotscheck -m aio_overpass --require-subclass -v
