name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - '.github/workflows/push_lint.yml'

      # source files
      - 'aio_overpass/**.py'
      - 'test/**.py'

      # dependency changes
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  lint:
    name: Lint package (3.11)
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check if pyproject.toml consistent with uv.lock
        run: uv lock --check

      - name: Install dependencies & library
        run: uv sync --all-extras --dev

      - name: Check formatting with Ruff
        run: uv run ruff format aio_overpass/ --check

      - name: Check formatting with Ruff (tests)
        if: always()  # keep going even if previous step failed
        run: uv run ruff format test/ --check

      - name: Lint with Ruff
        if: always()  # keep going even if previous step failed
        run: uv run ruff check aio_overpass/

      - name: Lint with Ruff (tests)
        if: always()  # keep going even if previous step failed
        run: uv run ruff check test/

      - name: Check types with mypy
        if: always()  # keep going even if previous step failed
        run: uv run mypy aio_overpass/

      - name: Validate __slots__
        if: always()  # keep going even if previous step failed
        run: uv run slotscheck -m aio_overpass --require-subclass -v

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Initialize
        uses: github/codeql-action/init@v3
        with:
          languages: python
          config-file: ./.github/codeql/codeql-config.yml

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Analyze
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
