# Run tests with combinations of major dependency releases.
#
# For numpy, the C API version matters:
# https://github.com/numpy/numpy/blob/main/numpy/core/code_generators/cversions.txt

name: Test different dependency versions

on:
  # quite a few jobs, so let's not run this on every push
  workflow_dispatch:
  schedule:
    # run once a day at 12:00 UTC
    - cron: '0 12 * * *'
    
jobs:
  test:
    name: Dependency matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12", "3.13"]
        aiohttp: ["3.11"]
        joblib: ["1.4"]
        networkx: ["3.2", "3.3", "3.4"]
        numpy: ["1.25", "1.26", "2.0", "2.1", "2.2"]
        shapely: ["2.0"]
        exclude:
          - python: "3.12"
            numpy: "1.25"
          - python: "3.13"
            numpy: "1.25"
          - python: "3.13"
            numpy: "1.26"
          - python: "3.13"
            numpy: "2.0"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies & library
        run: |
          poetry install --all-extras --no-interaction
          poetry add aiohttp=~${{ matrix.aiohttp }} --extras="speedups" --python="<=${{ matrix.python }}" --no-interaction
          poetry add joblib=~${{ matrix.joblib }} --python="<=${{ matrix.python }}" --no-interaction
          poetry add networkx=~${{ matrix.networkx }} --python="<=${{ matrix.python }}" --no-interaction
          poetry add shapely=~${{ matrix.shapely }} --python="<=${{ matrix.python }}" --no-interaction
          poetry add numpy=~${{ matrix.numpy }} --python="<=${{ matrix.python }}" --no-interaction

      - name: Test with pytest
        run: poetry run invoke test
